### ISSUE TITLE
How to deal with situations where setjmp/longjmp is used

### ISSUE THREAD

**Issue by stevefan1999-personal** [orangeduck/tgc#11]
Recently I've come into this access violation problem when I'm using tgc in combination with Bison, that when I free the internal state, it just tells me I cannot double-free a string while it is not in the root set nor was it in the freed set...

It seems like the GLR parser uses setjmp to revert to another state for parallel scanning, and so the stack order is completely scrambled, the stack address is not guaranteed under this situation, am I right about this?

**Comment by orangeduck** [comment]
Hi @stevefan1999,

Yeah I don't know exactly what might be wrong bug I'm fairly certain `tgc` wont place nicely with `setjmp` and `longjmp`. I'll add something about that to the FAQ but my advice for now would be to disable the GC until after bison is finished and then re-enable it again. It isn't a perfect solution but for now at least I'm not sure what else might be possible...

Thanks,

Dan
