### ISSUE TITLE
Stack iteration in tgc.c

### ISSUE THREAD

**Issue by marcusblake** [orangeduck/tgc#18]
Hi! Firstly, thank you for doing this! I'm a student trying to learn how to implement a garbage collector and reading your code has a great way to learn!

I have a question on how you go about traversing the gc roots in these [lines](https://github.com/orangeduck/tgc/blob/master/tgc.c#L194-#L196). In the for loop, why do you update pointer `p` by doing `p = ((char*)p) - sizeof(void*)` instead of something like `p = ((char*)p) - sizeof(char)`?

Perhaps my understanding of stack allocated variables is wrong, but why can you move the pointer 8 bytes down the stack instead of 1 byte? Why does this not cause you to overshoot pointing to the desired pointer value in some cases?

**Comment by marcusblake** [comment]
For example, why couldn't something like this occur?

```
                void *bottom ->  -----------   High address/bottom of stack
                                |           |
                                |   char a  |  1 byte
                                |           |
                                 -----------        
                                |           |
   (char*)p + sizeof(void*)  -> | char *str |  8 bytes
                                |           |
                                 ----------- 
                                |           |
                                |  int x    |  4 bytes
                                |           |
        void *p = void *top ->   ----------- 
                                |           |
                                | void *stk |  8 bytes
                                |           |
                                 -----------   Low address/top of stock
```

**Comment by orangeduck** [comment]
Hi @marcusblake,

Good question. The answer is simple - all pointers should be at memory addresses which are aligned with the pointer size. In this case it means that pointers will always be at memory addresses which are multiples of 8 bytes:

https://en.wikipedia.org/wiki/Data_structure_alignment

So what you draw in your diagram will not naturally occur. Instead you would expect to see 7 bytes of padding after the first `char` and before the `char*`, and 4 bytes of padding after the `int` and before the `void*`.

Hope that makes sense,

Dan

**Comment by marcusblake** [comment]
This makes perfect sense. Thank you so much for clearing that up!
