### ISSUE TITLE
Is embedded systems a goal?

### ISSUE THREAD

**Issue by beriberikix** [orangeduck/tgc#3]
I'm curious if you're targeting GC on microcontrollers. 64kb or less of memory, possibly 8-bit, etc.

For example, would you see this run on an AVR, i.e. Arduino? As [more](https://micropython.org/) [and](https://github.com/cesanta/v7) [more](https://github.com/hackndev/zinc) [languages](http://www.eluaproject.net/) make their way onto MCUs, GC would be a useful addition.

**Comment by orangeduck** [comment]
I'd love to see `tgc` run on embedded devices. For most devices I don't see any real reason why it wouldn't work, but it would require some testing and currently I don't own any.
