### ISSUE TITLE
Need free the old memory if realloc failed.

### ISSUE THREAD

**Issue by loggerhead** [orangeduck/tgc#4]
The old memory should freed in `tgc_realloc` because:

> For realloc(), the input pointer is still valid if reallocation failed.

``` c
  void *qtr = realloc(ptr, size);

  if (qtr == NULL) {
    // free(ptr);
    tgc_rem(gc, ptr);
    return qtr;
  }
```

**Comment by orangeduck** [comment]
I think it should be up to the caller of `tgc_realloc` to free the old pointer. Essentially `tgc_realloc` should match the semantics of `realloc`.

**Comment by loggerhead** [comment]
Oh, I don't consider this point, you are right 😄
